/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ColorPalette = IDL.Record({
  'accent' : IDL.Text,
  'background' : IDL.Text,
  'text' : IDL.Text,
  'secondary' : IDL.Text,
  'primary' : IDL.Text,
});
export const AnimeEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'summary' : IDL.Text,
  'genre' : IDL.Text,
  'colorPalette' : ColorPalette,
  'posterUrl' : IDL.Text,
  'animationPreset' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAnime' : IDL.Func([AnimeEntry], [], []),
  'deleteAnime' : IDL.Func([IDL.Nat], [], []),
  'getAllAnime' : IDL.Func([], [IDL.Vec(AnimeEntry)], ['query']),
  'getAnimeByGenre' : IDL.Func([IDL.Text], [IDL.Vec(AnimeEntry)], ['query']),
  'getAnimeById' : IDL.Func([IDL.Nat], [AnimeEntry], ['query']),
  'getColorPalettes' : IDL.Func([], [IDL.Vec(ColorPalette)], ['query']),
  'getGenres' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'updateAnime' : IDL.Func([IDL.Nat, AnimeEntry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ColorPalette = IDL.Record({
    'accent' : IDL.Text,
    'background' : IDL.Text,
    'text' : IDL.Text,
    'secondary' : IDL.Text,
    'primary' : IDL.Text,
  });
  const AnimeEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'summary' : IDL.Text,
    'genre' : IDL.Text,
    'colorPalette' : ColorPalette,
    'posterUrl' : IDL.Text,
    'animationPreset' : IDL.Text,
  });
  
  return IDL.Service({
    'addAnime' : IDL.Func([AnimeEntry], [], []),
    'deleteAnime' : IDL.Func([IDL.Nat], [], []),
    'getAllAnime' : IDL.Func([], [IDL.Vec(AnimeEntry)], ['query']),
    'getAnimeByGenre' : IDL.Func([IDL.Text], [IDL.Vec(AnimeEntry)], ['query']),
    'getAnimeById' : IDL.Func([IDL.Nat], [AnimeEntry], ['query']),
    'getColorPalettes' : IDL.Func([], [IDL.Vec(ColorPalette)], ['query']),
    'getGenres' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'updateAnime' : IDL.Func([IDL.Nat, AnimeEntry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };