/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnimeEntry {
  'id' : bigint,
  'title' : string,
  'summary' : string,
  'genre' : string,
  'colorPalette' : ColorPalette,
  'posterUrl' : string,
  'animationPreset' : string,
}
export interface ColorPalette {
  'accent' : string,
  'background' : string,
  'text' : string,
  'secondary' : string,
  'primary' : string,
}
export interface _SERVICE {
  'addAnime' : ActorMethod<[AnimeEntry], undefined>,
  'deleteAnime' : ActorMethod<[bigint], undefined>,
  'getAllAnime' : ActorMethod<[], Array<AnimeEntry>>,
  'getAnimeByGenre' : ActorMethod<[string], Array<AnimeEntry>>,
  'getAnimeById' : ActorMethod<[bigint], AnimeEntry>,
  'getColorPalettes' : ActorMethod<[], Array<ColorPalette>>,
  'getGenres' : ActorMethod<[], Array<string>>,
  'initialize' : ActorMethod<[], undefined>,
  'updateAnime' : ActorMethod<[bigint, AnimeEntry], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];